"""Added relationsips

Revision ID: c9ac2f4941be
Revises: 89263e942f9f
Create Date: 2025-02-23 15:49:09.275095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ac2f4941be'
down_revision: Union[str, None] = '89263e942f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'email')
    # ### end Alembic commands ###
